---
title: "CHIRPS_seasonalPrecipitation Admin_3"
author: "CHB"
date: '2022-06-23'
output: html_document
---

Packages
```{r}
library(dplyr)
library(moderndive)
library(readr)
library(tidyr)
library(tidyverse)
library(lubridate)
library(reshape2)
```

Read in Data
```{r}
pentadData <-read.csv("C:/Users/Catherine/OneDrive/Documents/2022_DSPG_Sahel/rainfall_ts_niger_admin3.csv")
```

Renaming the Columns
```{r}
for ( col in 1:ncol(pentadData)){
  colnames(pentadData)[col] <- sub("_precipitation", "", colnames(pentadData)[col])
}

for ( col in 1:ncol(pentadData)){
  colnames(pentadData)[col] <- sub("X", "", colnames(pentadData)[col])
}
head(pentadData)
```

Convert data from Wide to Long for years 1981 to 1994
```{r}
precipitationData <- pentadData %>%
  select(adm_03,adm_02,adm_01,rowcacode3, rowcacode2, rowcacode1, "19810101": "20220121")
precipitationDataLong <- gather(precipitationData, Date, Precipitation, "19810101":"20220121")
head(precipitationDataLong)
```

Convert Characters to Dates
```{r}
precipitationDataLong$Date <- ymd(precipitationDataLong$Date)
head(precipitationDataLong)
```

Convert Data to Year, Month, Day Columns
```{r}
Data <- precipitationDataLong %>%
  dplyr::mutate(year = lubridate::year(precipitationDataLong$Date), 
                month = lubridate::month(precipitationDataLong$Date), 
                day = lubridate::day(precipitationDataLong$Date))
```

Total Precipitation by Year Summary
```{r}
yearSum = Data %>% group_by(adm_03, year) %>%
  mutate(yearTotal_precipitation = sum(Precipitation, na.rm = FALSE),
            yearMean_precipitation = mean(Precipitation, na.rm = FALSE),
            yearMedian_precipitation = median(Precipitation, na.rm = FALSE))

```

Total Precipitation by Month Summary
```{r}
monthlySum = Data %>% group_by(adm_03, year, month) %>%
  summarize(total_precipitation = sum(Precipitation, na.rm = FALSE),
            mean_precipitation = mean(Precipitation, na.rm = FALSE),
            median_precipitation = median(Precipitation, na.rm = FALSE),
            standardDeviation_precipitation = sd(Precipitation, na.rm = FALSE),
            zScore_precipitation = (mean_precipitation/standardDeviation_precipitation))
```

###DO NOT RUN WILL BLOW UP PC
Seasonal Precipitation Summary
```{r}
seasonalPrecipitation <- monthlySum %>% 
  filter(month >= 5 & month <= 10) %>% 
  select(-month) %>%
  group_by(adm_03, year) %>% 
  summarize(Seasonal_Precipitation = sum(total_precipitation, na.rm = FALSE),
            mean_precipitation = mean(total_precipitation, na.rm = FALSE),
            median_precipitation = median(total_precipitation, na.rm = FALSE),
            zScore_precipitation = (periodData$baseMean_precipitation/standardDeviation_precipitation_))
            
view(seasonalPrecipitation)
```

1981 to 2010 Filtered
```{r}
periodData = seasonalPrecipitation %>% group_by(adm_03) %>%
  filter(year >= "1981" & year <= "2010") %>% 
  mutate(Total_precipitation = sum(Seasonal_Precipitation, na.rm = FALSE),
         baseMean_precipitation = mean(Seasonal_Precipitation, na.rm = FALSE),
         zScore_precipitation = (periodData$baseMean_precipitation/standardDeviation_precipitation_))
```

standard deviation and Z score

s<-sqrt(sum((v-mean(v))^2/(length(v)-1)))
```{r}
standardDeviation_precipitation_pt1 = (sum(seasonalPrecipitation$Seasonal_Precipitation - periodData$baseMean_precipitation))^2
standardDeviation_precipitation_pt2 = length(seasonalPrecipitation$Seasonal_Precipitation)-1
standardDeviation_precipitation_ = sqrt(standardDeviation_precipitation_pt1/standardDeviation_precipitation_pt2)




zScore_precipitation = (periodData$baseMean_precipitation/standardDeviation_precipitation_)
view(zScore_precipitation)
```


